# GUI Functionality Matrix

## Purpose

Define GUI parity expectations for core DJ surface modules so Product, Design, Engineering, and QA can validate behavior consistently.

## Evidence anchors

- `StarterMarked.png` — macro layout and top-level module placement
- `keyfeatures2.png` — browser/library depth and navigation affordances
- `automix.png` — deck and mixer interaction balance under automix/manual transitions

## Module parity matrix

| Module | User goal | Required controls | States (idle/active/error/loading) | Latency expectation | Keyboard/mouse interaction | Telemetry signal | Acceptance criteria |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Deck A / Deck B | Load, cue, and play a track on either deck with confidence during live operation. | Per deck: load/eject, play/pause, cue, sync, pitch/tempo fader, jog/scrub, elapsed/remaining timer, track title + BPM readout, level meter. | **Idle:** empty deck, load CTA visible. **Loading:** spinner/progress while metadata + waveform initialize. **Active:** playback/cue/sync controls responsive with live timers/meters. **Error:** failed load or unsupported media with clear retry path. | Deck load metadata appears ≤ 300 ms after selection; playback start response ≤ 80 ms from user action; transport display refresh at least every 100 ms. | Keyboard: assignable shortcuts for load, play/pause, cue, sync, nudge. Mouse: single-click control activation, drag for pitch/jog, scroll for fine nudge where supported. | `deck_track_loaded`, `deck_playback_toggled`, `deck_cue_set`, `deck_sync_toggled`, `deck_load_failed` (include `deck_id`, `track_id`, `duration_ms`). | QA can load independent tracks into both decks, start/stop either deck without cross-impact, trigger and recover from a forced bad-media load, and confirm deck balance/placement matches `automix.png` and `StarterMarked.png`. |
| Mixer | Blend deck outputs and route master/monitor levels safely without clipping. | Crossfader, channel faders, gain trims, EQ high/mid/low, filter knobs, master output, headphone cue select/volume, clip indicators. | **Idle:** neutral positions, meters at noise floor. **Active:** levels and EQ/filter updates reflected in real time. **Loading:** temporary disable while audio engine reconnects. **Error:** audio device unavailable, clipping lockout, or routing failure indicator. | Fader/EQ/filter control-to-audio response ≤ 50 ms; meter visual response ≤ 100 ms; routing fail/success banner within 500 ms. | Keyboard: optional coarse channel/crossfader nudges and cue toggles. Mouse: drag sliders, rotary knob drag, double-click reset to unity/default where defined. | `mixer_fader_changed`, `mixer_eq_changed`, `mixer_filter_changed`, `mixer_output_clipped`, `mixer_routing_error`. | QA can verify audible blend changes for each control, observe clip warning when intentionally overdriven, clear error by selecting valid device, and confirm deck-to-mixer balance behavior aligns with `automix.png`. |
| Waveform rail | Monitor phrasing, beats, and transitions to perform tight cueing and alignment. | Zoom in/out, horizontal scroll, beatgrid markers, playhead, cue/hotcue markers, optional phrase/section coloring, dual-deck overlay or split rails. | **Idle:** placeholder rail with no track. **Loading:** waveform render/progressive fill. **Active:** moving playhead + marker updates while playing/scrubbing. **Error:** waveform generation failure with fallback timing bar. | Initial waveform preview ≤ 500 ms after track load; full-resolution render ≤ 2 s for standard track length; scrub feedback ≤ 80 ms. | Keyboard: zoom shortcuts, cue marker jump keys, nudge left/right. Mouse: drag rail scrub, click-to-seek, wheel zoom centered on cursor. | `waveform_render_started`, `waveform_render_completed`, `waveform_seek`, `waveform_zoom_changed`, `waveform_render_failed`. | QA can observe progressive load then full waveform, execute click/drag seek with near-instant visual update, and validate fallback timing bar appears on forced waveform failure; macro position must align with `StarterMarked.png`. |
| Browser/library | Find, preview, and load content quickly from large libraries without losing context. | Search field, sortable columns (title/artist/BPM/key/duration), crate/folder tree, filters, preview player, load-to-deck actions, pagination/virtualized list. | **Idle:** empty/default collection view. **Loading:** list skeletons/spinners while querying. **Active:** results interactable with selection + preview. **Error:** query/read failure with retry and diagnostics hint. | Search/filter result update ≤ 250 ms for cached queries and ≤ 1 s p95 for uncached; row selection highlight ≤ 50 ms; preview start ≤ 120 ms. | Keyboard: focus search, typeahead, arrow row navigation, Enter preview/load, deck-target shortcuts. Mouse: click rows, double-click quick load, drag/drop to deck, resize columns. | `library_search_submitted`, `library_filter_applied`, `library_track_previewed`, `library_track_loaded_to_deck`, `library_query_failed`. | QA can retrieve deep-library items via search + filters, keyboard-load to chosen deck, and validate hierarchy depth/navigation parity against `keyfeatures2.png`; failed query state must retain user filter context after retry. |
| Sampler/pads | Trigger one-shots, stingers, and loops on demand during live programming. | Bank selector, per-pad trigger buttons, pad labels/colors, quantize toggle, stop-all, per-pad volume, latch/hold mode, sample assignment/edit. | **Idle:** pads armed and unlit/neutral. **Loading:** sample import/analysis indicator. **Active:** triggered pads show active state + playback progress where relevant. **Error:** missing file/decoder failure with reassignment prompt. | Pad trigger-to-audio latency ≤ 30 ms; bank switch visual feedback ≤ 80 ms; stop-all response ≤ 50 ms. | Keyboard: mapped pad triggers (e.g., number/function keys), bank switching, stop-all. Mouse: click/tap trigger, right-click/context for edit, drag sample onto pad. | `sampler_pad_triggered`, `sampler_bank_changed`, `sampler_sample_assigned`, `sampler_stop_all`, `sampler_trigger_failed`. | QA can trigger pads repeatedly without dropped inputs, switch banks while audio remains stable, recover from a removed sample file by reassignment flow, and confirm pad area placement matches `StarterMarked.png`. |
| FX and transitions | Apply transitions and effects cleanly to maintain broadcast energy and continuity. | FX rack enable/bypass, effect type selector, wet/dry, parameter knobs, beat-synced timing, transition presets (echo out, filter sweep, automix handoff), kill switch/reset. | **Idle:** FX bypassed, transition presets available. **Loading:** preset/effect chain init while locking unsafe controls. **Active:** enabled effects show current parameters and deck target. **Error:** DSP overload/invalid preset/device failure with safe bypass fallback. | Effect toggle response ≤ 60 ms; parameter modulation feedback ≤ 40 ms; transition preset trigger acknowledgement ≤ 80 ms; overload alert ≤ 200 ms. | Keyboard: quick-enable/bypass, next/previous preset, emergency kill. Mouse: click enable/preset, drag wet/dry and parameter knobs, hover for parameter readouts/tooltips. | `fx_enabled`, `fx_parameter_changed`, `transition_preset_triggered`, `fx_bypassed`, `fx_processing_error`. | QA can execute at least one manual transition and one automix handoff, observe immediate audible/visual response, trigger overload simulation to confirm safe bypass behavior, and verify transition flow parity with `automix.png`. |

## QA verification notes

- Acceptance criteria are pass/fail at row level; each row must pass before parity is considered complete.
- Telemetry events should be observable in the test logging pipeline with required identifiers populated.
- Any deviation from the evidence anchors (`StarterMarked.png`, `keyfeatures2.png`, `automix.png`) should be logged as a parity defect with screenshot comparison.
