from __future__ import annotations

import re
from pathlib import Path

import importlib.util
import sys

MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "roadmap_autopilot.py"
spec = importlib.util.spec_from_file_location("roadmap_autopilot", MODULE_PATH)
assert spec and spec.loader
ra = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = ra
spec.loader.exec_module(ra)


def _normalize_timestamp(content: str) -> str:
    return re.sub(
        r"Generated by `scripts/roadmap_autopilot\.py` at .*\.\n",
        "Generated by `scripts/roadmap_autopilot.py` at <timestamp>.\n",
        content,
    )


def test_build_plan_is_idempotent_except_timestamp(tmp_path: Path) -> None:
    todo_files = [Path(path) for path in ra.DEFAULT_TODO_FILES]
    tasks: list[ra.QueueItem] = []

    for markdown_path in todo_files:
        tasks.extend(
            ra.QueueItem(
                source=task.source,
                line_number=task.line_number,
                section=task.section,
                phase=task.phase,
                text=task.text,
                kind="todo",
            )
            for task in ra.collect_open_tasks(markdown_path)
        )

    tasks.sort(key=lambda item: (str(item.source), item.line_number))

    out = tmp_path / "unfinished-task-build-plan.md"
    ra.write_build_plan(tasks, out)
    first = out.read_text(encoding="utf-8")

    ra.write_build_plan(tasks, out)
    second = out.read_text(encoding="utf-8")

    assert _normalize_timestamp(first) == _normalize_timestamp(second)


def test_collect_open_tasks_reads_current_checkbox_state() -> None:
    tasks = ra.collect_open_tasks(Path("TODO_v1_1.md"))
    task_texts = {task.text for task in tasks}

    assert "Add guided restore flow in launcher/runtime startup path." not in task_texts
    assert (
        "End-to-end recovery path consistently completes in under 2 minutes." not in task_texts
    )
