from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
README_PATH = ROOT / 'README.md'
REQUIRED_DOCS = [
    Path('README.md'),
    Path('docs/PLANS.md'),
    Path('docs/DESIGN.md'),
    Path('docs/PRODUCT_SENSE.md'),
    Path('docs/RELIABILITY.md'),
    Path('docs/SECURITY.md'),
    Path('docs/operations/agent_execution_commands.md'),
    Path('docs/operations/subagent_execution_playbook.md'),
]
DOC_INDEX_START = '## 📁 Documentation Files'
DOC_INDEX_END = '## 🚀 Quick Start'
BUILD_PLAN_PATH = ROOT / 'docs' / 'exec-plans' / 'active' / 'unfinished-task-build-plan.md'
GENERATED_HEADER_PREFIX = 'Generated by `scripts/roadmap_autopilot.py` at '
TASK_ROW_PATTERN = re.compile(r'^- \[ \] `([^`]+):(\d+)` .* -> (.*\S)\s*$')
REMINDER_ROW_PATTERN = re.compile(r'^- (\d{4}-\d{2}-\d{2}) \| [^|]+ \| Owner: [^|]+ \| (.*\S)\s*$')


def _normalize_task_text(text: str) -> str:
    lowered = text.lower()
    stripped_links = re.sub(r'\[[^\]]+\]\([^\)]+\)', ' ', lowered)
    stripped_format = re.sub(r'[`*_#>]', ' ', stripped_links)
    collapsed = re.sub(r'[^a-z0-9]+', ' ', stripped_format)
    return ' '.join(collapsed.split())


def _check_required_docs() -> list[str]:
    missing = [doc for doc in REQUIRED_DOCS if not (ROOT / doc).exists()]
    if not missing:
        return []
    return [f'Missing required doc: {path.as_posix()}' for path in missing]


def _extract_readme_doc_index_lines(readme_text: str) -> list[str]:
    if DOC_INDEX_START not in readme_text or DOC_INDEX_END not in readme_text:
        return []
    section = readme_text.split(DOC_INDEX_START, maxsplit=1)[1].split(DOC_INDEX_END, maxsplit=1)[0]
    return [line.strip() for line in section.splitlines() if re.match(r'^\d+\.\s+', line.strip())]


def _check_readme_title(readme_text: str) -> list[str]:
    lines = readme_text.splitlines()
    h1_titles = [line.strip() for line in lines if line.startswith('# ')]
    if len(h1_titles) != 1:
        return [f'README.md must contain exactly one H1 title, found {len(h1_titles)}.']
    return []


def _check_readme_doc_index(readme_text: str) -> list[str]:
    errors: list[str] = []
    index_lines = _extract_readme_doc_index_lines(readme_text)
    if not index_lines:
        return ['README.md documentation index section not found or empty.']

    numbers = [int(re.match(r'^(\d+)\.', line).group(1)) for line in index_lines]
    expected = list(range(1, len(numbers) + 1))
    if numbers != expected:
        errors.append(
            'README.md documentation index numbering must be sequential starting at 1 '
            f'(found {numbers}, expected {expected}).'
        )

    return errors


def _check_unfinished_build_plan() -> list[str]:
    if not BUILD_PLAN_PATH.exists():
        return []

    errors: list[str] = []
    text = BUILD_PLAN_PATH.read_text(encoding='utf-8')
    lines = text.splitlines()

    generated_header_count = sum(
        1 for line in lines if line.startswith(GENERATED_HEADER_PREFIX)
    )
    if generated_header_count != 1:
        errors.append(
            'unfinished-task-build-plan.md must contain exactly one generated header '
            f'(found {generated_header_count}).'
        )

    task_keys: dict[tuple[str, int, str], int] = {}
    reminder_keys: dict[tuple[str, int, str], int] = {}
    in_reminder_section = False

    for line in lines:
        if line.startswith('## Cadence Due-Date Reminders'):
            in_reminder_section = True
            continue
        if line.startswith('## ') and not line.startswith('## Cadence Due-Date Reminders'):
            in_reminder_section = False

        task_match = TASK_ROW_PATTERN.match(line)
        if task_match:
            source_file = task_match.group(1)
            line_ref = int(task_match.group(2))
            normalized_text = _normalize_task_text(task_match.group(3))
            key = (source_file, line_ref, normalized_text)
            task_keys[key] = task_keys.get(key, 0) + 1
            continue

        if in_reminder_section:
            reminder_match = REMINDER_ROW_PATTERN.match(line)
            if reminder_match:
                line_ref = int(reminder_match.group(1).replace('-', ''))
                normalized_text = _normalize_task_text(reminder_match.group(2))
                key = ('TODO.md', line_ref, normalized_text)
                reminder_keys[key] = reminder_keys.get(key, 0) + 1

    duplicate_tasks = [key for key, count in task_keys.items() if count > 1]
    if duplicate_tasks:
        errors.append(
            'unfinished-task-build-plan.md contains duplicate task keys '
            f'(source_file,line_ref,normalized_task_text): {duplicate_tasks[:5]}'
        )

    duplicate_reminders = [key for key, count in reminder_keys.items() if count > 1]
    if duplicate_reminders:
        errors.append(
            'unfinished-task-build-plan.md contains duplicate reminder keys '
            f'(source_file,line_ref,normalized_task_text): {duplicate_reminders[:5]}'
        )

    return errors


def main() -> int:
    failures: list[str] = []
    failures.extend(_check_required_docs())

    readme_text = README_PATH.read_text(encoding='utf-8')
    failures.extend(_check_readme_title(readme_text))
    failures.extend(_check_readme_doc_index(readme_text))
    failures.extend(_check_unfinished_build_plan())

    if failures:
        print('Documentation consistency check failed:')
        for failure in failures:
            print(f'- {failure}')
        return 1

    print(
        'Documentation consistency check passed '
        f'({len(REQUIRED_DOCS)} required docs + README structure checks).'
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
